#!/bin/sh

echo
echo Rebuilding all the Perl RPMs for your version of Perl
echo
sleep 2

while read F
do
  if [ -f ${F}.src.rpm ]; then
    rpmbuild --rebuild ${F}.src.rpm >/dev/null
  else
    echo Missing file ${F}.src.rpm. Are you in the right directory\?
  fi
done << EOF
perl-Convert-TNEF-0.17-1
perl-File-Spec-0.82-1
perl-File-Temp-0.12-1
perl-HTML-Parser-3.26-1
perl-HTML-Tagset-3.03-1
perl-IO-stringy-2.108-1
perl-MailTools-1.50-1
perl-MIME-Base64-2.12-1
perl-MIME-tools-5.411-1
perl-MIME-tools-5.411-pl3.1
perl-TimeDate-1.1301-1
EOF

echo
echo Now to install them all.
echo Do not worry if you get some errors from this...
echo
sleep 2

while read F
do
  if [ -f /usr/src/redhat/RPMS/noarch/${F}.noarch.rpm ]; then
    rpm -Uvh /usr/src/redhat/RPMS/noarch/${F}.noarch.rpm
  else
    echo Missing file /usr/src/redhat/RPMS/noarch/${F}.noarch.rpm.
    echo Maybe it did not build correctly\?
  fi
done << EOF
perl-Convert-TNEF-0.17-1
perl-File-Spec-0.82-1
perl-File-Temp-0.12-1
perl-HTML-Tagset-3.03-1
perl-IO-stringy-2.108-1
perl-MailTools-1.50-1
perl-MIME-tools-5.411-1
perl-MIME-tools-5.411-pl3.1
perl-TimeDate-1.1301-1
EOF

while read F
do
  if [ -f /usr/src/redhat/RPMS/i386/${F}.i386.rpm ]; then
    rpm -Uvh /usr/src/redhat/RPMS/i386/${F}.i386.rpm >/dev/null
  else
    echo Missing file /usr/src/redhat/RPMS/i386/${F}.i386.rpm.
    echo Maybe it did not build correctly\?
  fi
done << EOF
perl-HTML-Parser-3.26-1
perl-MIME-Base64-2.12-1
EOF

echo
echo Now to install MailScanner itself.
echo
sleep 2

rpm -Uvh mailscanner*noarch.rpm

