Name: perl-MIME-Base64
Version: 3.07
Release: 1
Packager: Julian Field <mailscanner@ecs.soton.ac.uk>
Summary: MIME-Base64 Perl module
License: distributable
Group: Development/Libraries
URL: http://search.cpan.org/search?mode=module&query=MIME%3a%3aBase64
BuildRoot: %{_tmppath}/%{name}-root
Source0: MIME-Base64-3.07.tar.gz
#Patch0: mime-base64.patch1.txt

%description
MIME-Base64 Perl module
%prep
%setup -q -n MIME-Base64-%{version} 1
#%patch0 -p1

%build
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL PREFIX=$RPM_BUILD_ROOT/usr 
make
make test

%clean
rm -rf $RPM_BUILD_ROOT
%install

rm -rf $RPM_BUILD_ROOT
eval `perl '-V:installarchlib'`
mkdir -p $RPM_BUILD_ROOT/$installarchlib
make install

[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress

find $RPM_BUILD_ROOT/usr -type f -print | \
	sed "s@^$RPM_BUILD_ROOT@@g" | \
	grep -v perllocal.pod | \
	grep -v "\.packlist" > MIME-Base64-%{version}-filelist
if [ "$(cat MIME-Base64-%{version}-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit 1
fi

%files -f MIME-Base64-%{version}-filelist
%defattr(-,root,root)

%changelog
* Fri Jun 06 2007 Julian Field <mailscanner@ecs.soton.ac.uk>
- Updated for 3.07-1
* Sun Oct 06 2002 Julian Field <mailscanner@ecs.soton.ac.uk>
- Specfile autogenerated

