#!/bin/sh
### BEGIN INIT INFO
# Provides:          MailScanner
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the Mailscanner daemon
# Description:       starts MailScanner using start-stop-daemon
### END INIT INFO

# Author: Jerry Benton <mailscanner@mailborder.com>

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/usr/sbin:/usr/bin:/bin:/sbin
DESC="email processor - "
NAME=MailScanner
PNAME=MailScanner
DAEMON=/usr/sbin/$NAME
STARTAS=MailScanner
SCRIPTNAME=/etc/init.d/$PNAME
CONFFILE=/etc/MailScanner/MailScanner.conf
QUICKPEEK=/usr/sbin/Quick.Peek
run_mailscanner=0
run_nice=0
stopped_lockfile=/var/lock/subsys/MailScanner.off

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# if /var/lock/subsys is missing
[ -d /var/lock/subsys ] || mkdir -p /var/lock/subsys

# Read configuration variable file if it is present
[ -r /etc/default/$PNAME ] && . /etc/default/$PNAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# make this script show Starting / Stopping / etc ...
VERBOSE=yes

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

# Don't start if MailScanner is not configured
if [ $run_mailscanner = 0 ]; then
    if [ -z "$satisfy_nitpicking_on_removal" ]; then
	cat <<-EOF

	Edit the file /etc/MailScanner/MailScanner.conf according to
	your needs. When complete, edit /etc/default/MailScanner and set 
	the variable to enable MailScanner to run:

	run_mailscanner = 1

	EOF
    fi
    exit 0
fi

user=`${QUICKPEEK} RunAsUser ${CONFFILE}`
group=`${QUICKPEEK} RunAsGroup ${CONFFILE}`
PIDFILE=`${QUICKPEEK} pidfile ${CONFFILE}`

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --start --quiet --startas $STARTAS --pidfile $PIDFILE --test > /dev/null || return 1
	start-stop-daemon --start --quiet --nicelevel $run_nice --exec $DAEMON --pidfile $PIDFILE -- $DAEMON_ARGS || return 2

  # Set lockfile to inform cronjobs about the running daemon
	RETVAL="$?"
	if [ $RETVAL -eq 0 ]; then
	    touch /run/lock/subsys/MailScanner
	    rm -f $stopped_lockfile
	fi
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon --stop --quiet --retry=TERM/10/TERM/20 --pidfile $PIDFILE
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2

  # Remove lockfile for cronjobs
	if [ $RETVAL -eq 0 ]; then
	    rm -f /run/lock/subsys/MailScanner
	    touch $stopped_lockfile
	fi
	return "$RETVAL"
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE
	return 0
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  reload|force-reload)
	log_daemon_msg "Reloading $DESC" "$NAME"
	do_reload
	log_end_msg $?
	;;
  restart)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|force-reload}" >&2
	exit 3
	;;
esac
: