#!/bin/sh
# postinst script for MailScanner
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# group for users to run under
if ! getent group mtagroup >/dev/null 2>&1; then
	groupadd -f mtagroup >/dev/null 2>&1
fi

# check for common users and add to the mtagroup
if id -u clam >/dev/null 2>&1; then
	usermod -a -G mtagroup clam >/dev/null 2>&1
fi

if id -u clamav >/dev/null 2>&1; then
	usermod -a -G mtagroup clamav >/dev/null 2>&1
fi

if id -u vscan >/dev/null 2>&1; then
	usermod -a -G mtagroup vscan >/dev/null 2>&1
fi

if id -u sophosav >/dev/null 2>&1; then
	usermod -a -G mtagroup sophosav >/dev/null 2>&1
fi

if id -u Debian-exim >/dev/null 2>&1; then
	usermod -a -G mtagroup Debian-exim >/dev/null 2>&1
fi

if id -u postfix >/dev/null 2>&1; then
	usermod -a -G mtagroup postfix >/dev/null 2>&1
fi

if id -u mail >/dev/null 2>&1; then
	usermod -a -G mtagroup mail >/dev/null 2>&1
fi

if [ -d "/var/spool/exim4.in" ]; then
	install -d -oDebian-exim -gmtagroup -m0750 /var/spool/exim4.in
	install -d -oDebian-exim -gmtagroup -m0750 /var/spool/exim4.in/db
	install -d -oDebian-exim -gmtagroup -m0750 /var/spool/exim4.in/input
	install -d -oDebian-exim -gmtagroup -m0750 /var/spool/exim4.in/msglog
fi

if [ ! -d "/var/spool/mqueue.in" ]; then
	perl -pi -e 's{Incoming Queue Dir = /var/spool/mqueue.in}{Incoming Queue Dir = /var/spool/mqueue}g;' /etc/MailScanner/MailScanner.conf
fi

# lock down some directory permissions
install -d -omail -gmtagroup -m0755 /var/run/MailScanner
install -d -omail -gmtagroup -m0750 /var/spool/MailScanner/archive
install -d -omail -gmtagroup -m0750 /var/spool/MailScanner/incoming
install -d -omail -gmtagroup -m0750 /var/spool/MailScanner/incoming
install -d -omail -gmtagroup -m0750 /var/spool/MailScanner/quarantine

# upgrade
if [ -f "/etc/MailScanner/MailScanner.conf.original323" ]; then

cp -f /etc/MailScanner/MailScanner.conf /etc/MailScanner/MailScanner.conf.dpkg-dist

while read f 
do
  mv -f /etc/MailScanner/$f.original323 /etc/MailScanner/$f
done << EOF
filename.rules.conf
filetype.rules.conf
archives.filename.rules.conf
archives.filetype.rules.conf
MailScanner.conf
spam.assassin.prefs.conf
virus.scanners.conf
phishing.safe.sites.conf
phishing.bad.sites.conf
EOF

# removed for 4.86.1 - add back later
#spam.lists.conf
#country.domains.conf

fi

# upgrade
if [ -f "/etc/default/MailScanner.original323" ]; then
	rm -f /etc/default/MailScanner
	mv /etc/default/MailScanner.original323 /etc/default/MailScanner
fi

# upgrade correction
if [ -f "/etc/MailScanner/CustomConfig.pm" ]; then
	cp -uf /etc/MailScanner/CustomConfig.pm /usr/share/MailScanner/perl/MailScanner/CustomConfig.pm
	rm -f /etc/MailScanner/CustomConfig.pm
fi

rm -f /etc/MailScanner/*.original323

# softlink for custom functions
ln -s /usr/share/MailScanner/perl/custom/ /etc/MailScanner/custom

update-rc.d MailScanner defaults

if [ -f "/etc/MailScanner/conf.d/z_48611_upgrade.conf" ]; then
	echo "WARNING WARNING WARNING WARNING";
	echo;
	echo "An upgrade was detected. Note that these items have changed:";
	echo "- spam.lists.conf";
	echo "- country.domains.conf";
	echo "- the MailScanner directory structure";
	echo;
	echo "The file /etc/MailScanner/conf.d/z_48611_upgrade.conf has been";
	echo "created to address some key items you should check!";
	echo;
fi

exit 0
