#!/bin/sh
# postinst script for mailscanner
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# group for users to run under
if ! getent group mtagroup >/dev/null 2>&1; then
	groupadd -f mtagroup >/dev/null 2>&1
fi

# check for common users and add to the mtagroup
if id -u clam >/dev/null 2>&1; then
	usermod -a -G mtagroup clam >/dev/null 2>&1
fi

if id -u clamav >/dev/null 2>&1; then
	usermod -a -G mtagroup clamav >/dev/null 2>&1
fi

if id -u vscan >/dev/null 2>&1; then
	usermod -a -G mtagroup vscan >/dev/null 2>&1
fi

if id -u Debian-exim >/dev/null 2>&1; then
	usermod -a -G mtagroup Debian-exim >/dev/null 2>&1
fi

if id -u postfix >/dev/null 2>&1; then
	usermod -a -G mtagroup postfix >/dev/null 2>&1
fi

if id -u mail >/dev/null 2>&1; then
	usermod -a -G mtagroup mail >/dev/null 2>&1
fi

if [ -d "/var/spool/exim4.in" ]; then
	install -d -oDebian-exim -gmtagroup -m0750 /var/spool/exim4.in
	install -d -oDebian-exim -gmtagroup -m0750 /var/spool/exim4.in/db
	install -d -oDebian-exim -gmtagroup -m0750 /var/spool/exim4.in/input
	install -d -oDebian-exim -gmtagroup -m0750 /var/spool/exim4.in/msglog
fi

if [ ! -d "/var/spool/mqueue.in" ]; then
	perl -pi -e 's{Incoming Queue Dir = /var/spool/mqueue.in}{Incoming Queue Dir = /var/spool/mqueue}g;' /etc/MailScanner/MailScanner.conf
fi

# copy old ms files if this is an upgrade
if [ -d "/usr/lib/MailScanner" ]; then
	cp -f /usr/lib/MailScanner/MailScanner/CustomFunctions/* /usr/share/MailScanner/MailScanner/CustomFunctions/
	rm -rf /usr/lib/MailScanner
fi

# this is not in the new mailscanner package. move it
if [ -d "/etc/MailScanner/CustomFunctions" ]; then
	cp -f /etc/MailScanner/CustomFunctions/* /usr/share/MailScanner/MailScanner/CustomFunctions/
	rm -rf /etc/MailScanner/CustomFunctions
	ln -s /usr/share/MailScanner/MailScanner/CustomFunctions/ /etc/MailScanner/CustomFunctions
fi

# this is not in the new mailscanner package.
if [ -d "/etc/MailScanner/autoupdate" ]; then
	rm -rf /etc/MailScanner/autoupdate
	ln -s /usr/share/MailScanner/MailScanner/autoupdate/ /etc/MailScanner/autoupdate
fi

# this is not in the new mailscanner package.
if [ -d "/etc/MailScanner/wrapper" ]; then
	rm -rf /etc/MailScanner/wrapper
	ln -s /usr/share/MailScanner/MailScanner/wrapper/ /etc/MailScanner/wrapper
fi


install -d -omail -gmtagroup -m0775 /var/run/MailScanner
install -d -omail -gmtagroup -m0775 /var/spool/MailScanner/archive
install -d -omail -gmtagroup -m0775 /var/spool/MailScanner/incoming
install -d -omail -gmtagroup -m0775 /var/spool/MailScanner/incoming
install -d -omail -gmtagroup -m0775 /var/spool/MailScanner/quarantine

# upgrade
if [ -f "/etc/MailScanner/MailScanner.conf.original323" ]; then

cp -f /etc/MailScanner/MailScanner.conf /etc/MailScanner/MailScanner.conf.dpkg-dist

while read f 
do
  mv -f /etc/MailScanner/$f.original323 /etc/MailScanner/$f
done << EOF
filename.rules.conf
filetype.rules.conf
archives.filename.rules.conf
archives.filetype.rules.conf
MailScanner.conf
spam.assassin.prefs.conf
spam.lists.conf
virus.scanners.conf
phishing.safe.sites.conf
phishing.bad.sites.conf
country.domains.conf
EOF

fi

# upgrade
if [ -f "/etc/default/mailscanner.original323" ]; then
	rm -f /etc/default/mailscanner
	mv /etc/default/mailscanner.original323 /etc/default/mailscanner
fi

# upgrade correction
if [ -f "/etc/MailScanner/CustomConfig.pm" ]; then
	cp -f /etc/MailScanner/CustomConfig.pm /usr/share/MailScanner/MailScanner/CustomConfig.pm
	rm -f /etc/MailScanner/CustomConfig.pm
	ln -s /usr/share/MailScanner/MailScanner/CustomConfig.pm /etc/MailScanner/CustomConfig.pm
fi

exit 0
