#!/bin/sh
#
# preinst script for mailscanner

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


# this makes copies of original conf files. 
# the postinst script will move them back
if [ -f "/etc/MailScanner/MailScanner.conf" ]; then

	if [ -d "/etc/MailScanner/conf.d" ]; then
		# we need to ensure that the new directory structure is applied
		echo '%report-dir% = /usr/share/MailScanner/reports/en' > /etc/MailScanner/conf.d/z_48611_upgrade.conf
		echo 'Custom Functions Dir = /usr/share/MailScanner/perl/custom' >> /etc/MailScanner/conf.d/z_48611_upgrade.conf
		echo 'Monitors for ClamAV Updates = /usr/local/share/clamav/*.cld /usr/local/share/clamav/*.cvd /var/lib/clamav/*.inc/* /var/lib/clamav/*.?db /var/lib/clamav/*.cvd' >> /etc/MailScanner/conf.d/z_48611_upgrade.conf
	fi
		
	if [ -f "/etc/default/mailscanner" ]; then
		cp -f /etc/default/mailscanner /etc/default/MailScanner.original323
	fi

	if [ -f "/etc/default/MailScanner" ]; then
		cp -f /etc/default/MailScanner /etc/default/MailScanner.original323
	fi

while read f 
do
  cp /etc/MailScanner/$f /etc/MailScanner/$f.original323
done << EOF
filename.rules.conf
filetype.rules.conf
archives.filename.rules.conf
archives.filetype.rules.conf
MailScanner.conf
spam.assassin.prefs.conf
spam.lists.conf
virus.scanners.conf
phishing.safe.sites.conf
phishing.bad.sites.conf
country.domains.conf
EOF

fi

exit 0
