Name: perl-MIME-tools
Version: 5.427
Release: 2
Packager: Julian Field <mailscanner@ecs.soton.ac.uk>
Summary: MIME-tools Perl module
License: distributable
Group: Development/Libraries
URL: http://search.cpan.org/search?mode=module&query=MIME%3a%3atools
BuildRoot: %{_tmppath}/%{name}-root
Buildarch: noarch
BuildRequires: perl-IO-stringy
Requires: perl-IO-stringy, perl-MailTools
Source0: MIME-tools-5.427.tar.gz
#Patch0: mime-tools-5.415-patch1.txt
#Patch1: mime-tools-5.415-patch2.txt
#Patch1: mime-tools-patch2.txt
#Patch2: mime-tools-patch3.txt
#Patch3: mime-tools-patch4.txt

%description
MIME-tools Perl module
%prep
%setup -q -n MIME-tools-%{version} 1
#%patch0 -p1
#%patch1 -p1
#%patch2 -p1
#%patch3 -p1

%build
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL
make
# Skip this as it will fail due to missing MIME::Base64 make test
make test

%clean
rm -rf $RPM_BUILD_ROOT
%install

rm -rf $RPM_BUILD_ROOT
eval `perl '-V:installarchlib'`
mkdir -p $RPM_BUILD_ROOT/$installarchlib
make install DESTDIR=$RPM_BUILD_ROOT

[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress

find $RPM_BUILD_ROOT/usr -type f -print | \
	sed "s@^$RPM_BUILD_ROOT@@g" | \
	grep -v perllocal.pod | \
	grep -v "\.packlist" > MIME-tools-%{version}-filelist
if [ "$(cat MIME-tools-%{version}-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit 1
fi

%files -f MIME-tools-%{version}-filelist
%defattr(-,root,root)

%changelog
* Fri Oct 04 2002 Julian Field <mailscanner@ecs.soton.ac.uk>
- Specfile autogenerated

