Name: perl-Convert-TNEF
Version: 0.17
Release: 2
Packager: mailscanner@ecs.soton.ac.uk
Summary: Convert-TNEF Perl module
License: distributable
Group: Development/Libraries
URL: http://search.cpan.org/search?mode=module&query=Convert%3a%3aTNEF
BuildRoot: %{_tmppath}/%{name}-root
BuildRequires: perl >= 0:5.00503
Requires: perl, perl-MIME-tools
Buildarch: noarch
Source0: Convert-TNEF-0.17.tar.gz

%description
Convert-TNEF Perl module
%prep
%setup -q -n Convert-TNEF-%{version} 1

%build
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL
make
make test

%clean
rm -rf $RPM_BUILD_ROOT
%install

rm -rf $RPM_BUILD_ROOT
eval `perl '-V:installarchlib'`
mkdir -p $RPM_BUILD_ROOT/$installarchlib
make install DESTDIR=$RPM_BUILD_ROOT

[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress

find $RPM_BUILD_ROOT/usr -type f -print | \
	sed "s@^$RPM_BUILD_ROOT@@g" | \
	grep -v perllocal.pod | \
	grep -v "\.packlist" > Convert-TNEF-0.17-filelist
if [ "$(cat Convert-TNEF-0.17-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit 1
fi

%files -f Convert-TNEF-0.17-filelist
%defattr(-,root,root)

%changelog
* Sun Sep 29 2002 mailscanner@ecs.soton.ac.uk
- Specfile autogenerated

