Name: perl-HTML-Tagset
Version: 3.03
Release: 2
Packager: mailscanner@ecs.soton.ac.uk
Summary: HTML-Tagset Perl module
License: distributable
Group: Development/Libraries
URL: http://search.cpan.org/search?mode=module&query=HTML%3a%3aTagset
BuildRoot: %{_tmppath}/%{name}-root
BuildRequires: perl >= 0:5.00503
Buildarch: noarch
Source0: HTML-Tagset-3.03.tar.gz

%description
HTML-Tagset Perl module
%prep
%setup -q -n HTML-Tagset-%{version} 1

%build
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL
make
make test

%clean
rm -rf $RPM_BUILD_ROOT
%install

rm -rf $RPM_BUILD_ROOT
eval `perl '-V:installarchlib'`
mkdir -p $RPM_BUILD_ROOT/$installarchlib
make install DESTDIR=$RPM_BUILD_ROOT

[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress

find $RPM_BUILD_ROOT/usr -type f -print | \
	sed "s@^$RPM_BUILD_ROOT@@g" | \
	grep -v perllocal.pod | \
	grep -v "\.packlist" > HTML-Tagset-3.03-filelist
if [ "$(cat HTML-Tagset-3.03-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit 1
fi

%files -f HTML-Tagset-3.03-filelist
%defattr(-,root,root)

%changelog
* Sat Oct 05 2002 mailscanner@ecs.soton.ac.uk
- Specfile autogenerated

