Summary: Sys-Hostname-Long Perl module
Name: perl-Sys-Hostname-Long
Version: 1.4
Release: 2
Packager: mailscanner@ecs.soton.ac.uk
License: GPL or Artistic
Group: Development/Libraries
URL: http://search.cpan.org/dist/Sys-Hostname-Long/
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root
BuildArch: noarch
#BuildRequires: perl >= 0:5.00503
Source0: Sys-Hostname-Long-1.4.tar.gz

%description
Sys-Hostname-Long Perl module

%description
Sys-Hostname-Long Perl module
%prep
%setup -q -n Sys-Hostname-Long-%{version} 1

%build
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL
make
make test

%clean
rm -rf $RPM_BUILD_ROOT
%install

rm -rf $RPM_BUILD_ROOT
eval `perl '-V:installarchlib'`
mkdir -p $RPM_BUILD_ROOT/$installarchlib
make install DESTDIR=$RPM_BUILD_ROOT

[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress

find $RPM_BUILD_ROOT/usr -type f -print | \
	sed "s@^$RPM_BUILD_ROOT@@g" | \
	grep -v perllocal.pod | \
	grep -v "\.packlist" > Sys-Hostname-Long-%{version}-filelist
if [ "$(cat Sys-Hostname-Long-%{version}-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit 1
fi

%files -f Sys-Hostname-Long-%{version}-filelist
%defattr(-,root,root)

%changelog
* Tue May 23 2006 Julian Field <mailscanner@ecs.soton.ac.uk>
- Specfile autogenerated

