Name: perl-Convert-BinHex
Version: 1.119
Release: 3
Packager: mailscanner@ecs.soton.ac.uk
Summary: Convert-BinHex Perl module
License: distributable
Group: Development/Libraries
URL: http://search.cpan.org/search?mode=module&query=Convert%3a%3aBinHex
BuildRoot: %{_tmppath}/%{name}-root
#BuildRequires: perl >= 0:5.00503
Buildarch: noarch
Source0: Convert-BinHex-1.119.tar.gz

%description
Convert-BinHex Perl module
%prep
%setup -q -n Convert-BinHex-%{version} 1

%build
#CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL PREFIX=$RPM_BUILD_ROOT/usr
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL
make

%clean
rm -rf $RPM_BUILD_ROOT
%install

rm -rf $RPM_BUILD_ROOT
eval `perl '-V:installarchlib'`
mkdir -p $RPM_BUILD_ROOT/$installarchlib
make install DESTDIR=$RPM_BUILD_ROOT

[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress

find $RPM_BUILD_ROOT/usr -type f -print | \
	sed "s@^$RPM_BUILD_ROOT@@g" | \
	grep -v perllocal.pod | \
	grep -v "\.packlist" > Convert-BinHex-1.119-filelist
if [ "$(cat Convert-BinHex-1.119-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit 1
fi

%files -f Convert-BinHex-1.119-filelist
%defattr(-,root,root)

%changelog
* Sat Oct 05 2002 mailscanner@ecs.soton.ac.uk
- Specfile autogenerated

