Summary: Digest-SHA1 Perl module
Name: perl-Digest-SHA1
Version: 2.11
Release: 3
Packager: mailscanner@ecs.soton.ac.uk
License: GPL or Artistic
Group: Development/Libraries
URL: http://search.cpan.org/dist/Digest-SHA1/
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root
#BuildArch: noarch
#BuildRequires: perl >= 0:5.00503
Source0: Digest-SHA1-2.11.tar.gz

%description
Digest-SHA1 Perl module

%description
Digest-SHA1 Perl module
%prep
%setup -q -n Digest-SHA1-%{version} 1

%build
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL
make
make test

%clean
rm -rf $RPM_BUILD_ROOT
%install

rm -rf $RPM_BUILD_ROOT
eval `perl '-V:installarchlib'`
mkdir -p $RPM_BUILD_ROOT/$installarchlib
make install DESTDIR=$RPM_BUILD_ROOT

[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress

find $RPM_BUILD_ROOT/usr -type f -print | \
	sed "s@^$RPM_BUILD_ROOT@@g" | \
	grep -v perllocal.pod | \
	grep -v "\.packlist" > Digest-SHA1-%{version}-filelist
if [ "$(cat Digest-SHA1-%{version}-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit 1
fi

%files -f Digest-SHA1-%{version}-filelist
%defattr(-,root,root)

%changelog
* Fri Mar 14 2008 Julian Field <mailscanner@ecs.soton.ac.uk>
- Specfile autogenerated

