#!/bin/sh

# css-wrapper --	invoke Symantec Carrier Scan for use with mailscanner
#
#   MailScanner - SMTP E-Mail Virus Scanner
#   Copyright (C) 2001  Julian Field
#
#   $Id: css-wrapper 2256 2004-02-27 12:34:07Z jkf $
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#   The author, Julian Field, can be contacted by email at
#      Jules@JulianField.net
#   or by paper mail at
#      Julian Field
#      Dept of Electronics & Computer Science
#      University of Southampton
#      Southampton
#      SO17 1BJ
#      United Kingdom
#
#

#!/bin/sh
  
PackageDir=$1
SCAN=${PackageDir}/bin/cscmdline
CONFIG=${PackageDir}/bin/cscmdline.cfg
SCANOPTIONS="-C $CONFIG -i 1 -l -r -v"
shift
  
if [ "x$1" = "x-IsItInstalled" ]; then
  [ -x $SCAN ] && exit 0
  exit 1
fi

cd $1
  
$SCAN $SCANOPTIONS `pwd` 

