#!/bin/sh

# etrust-wrapper --	invoke eTrustAntivirus for use with mailscanner
#
#   MailScanner - SMTP E-Mail Virus Scanner
#   Copyright (C) 2001  Julian Field
#
#   $Id: etrust-wrapper 4253 2007-12-26 21:37:20Z sysjkf $
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#   The author, Julian Field, can be contacted by email at
#      Jules@JulianField.net
#   or by paper mail at
#      Julian Field
#      Dept of Electronics & Computer Science
#      University of Southampton
#      Southampton
#      SO17 1BJ
#      United Kingdom
#
#

PackageDir=$1
shift

if [ -x "${PackageDir}/eTrustITM/ino/bin/inocmd32" ]; then
  PackageDir=${PackageDir}/eTrustITM
fi

CAIGLBL0000=${PackageDir}
export CAIGLBL0000
LD_LIBRARY_PATH=${PackageDir}/ino/config:${PackageDir}/ino/lib
export LD_LIBRARY_PATH

ScanOptions=""
prog=${PackageDir}/ino/bin/inocmd32

if [ "x$1" = "x-IsItInstalled" ]; then
  [ -x $prog ] && exit 0
  exit 1
fi

exec $prog $ScanOptions "$@"

