#!/bin/sh

# vexira-wrapper --	invoke Vexira for use with mailscanner
#
#   MailScanner - SMTP E-Mail Virus Scanner
#   Copyright (C) 2001  Julian Field
#
#   $Id: vexira-wrapper 4330 2008-03-11 16:20:39Z sysjkf $
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#   The author, Julian Field, can be contacted by email at
#      Jules@JulianField.net
#   or by paper mail at
#      Julian Field
#      Dept of Electronics & Computer Science
#      University of Southampton
#      Southampton
#      SO17 1BJ
#      United Kingdom
#
#

PackageDir=$1
shift

if [ "x$1" = "x-IsItInstalled" ]; then
  # Cope with new version
  [ -x ${PackageDir}/vascan ] && exit 0
  [ -x ${PackageDir}/vexira ] && exit 0
  exit 1
fi

if [ -x ${PackageDir}/vascan ]; then
  exec ${PackageDir}/vascan --config=/etc/vexira/vascan.ini --vdb=/var/lib/vascan/vdb9.xml --engine=/usr/lib/libvbengine.so "$@"
elif [ -x ${PackageDir}/vexira ]; then
  exec ${PackageDir}/vexira "$@"
fi
exit 1

